### ISSUE TITLE
PIROptimizer: Error when writing optimization data, aborting.

### ISSUE THREAD

**Issue by mortendahl** [XPIR-team/XPIR#12]
Hi,

I receive error `PIROptimizer: Error when writing optimization data, aborting.` from the server when trying to do a query. Any ideas what could cause this? 

I'm compiling on Ubuntu 14.04 running in docker. At first I had trouble finishing the `check-correctness.sh` script but it went through after I granted more virtual memory -- wondering if this could play a part in the error from the optimiser?

Thanks in advance,
Morten

**Comment by Kirija** [comment]
Hi Morten,

I guess that you need a directory called « exp » in both the server and the client directories.

Hope this helps,
Marco

**Comment by mortendahl** [comment]
Hi Marco,

Thanks a lot for the quick answer! It did indeed solve the issue.

/Morten

**Comment by carlosaguilarmelchor** [comment]
Dear Morten,
we have finally released the new version of XPIR "XPIR as a lib" (see https://github.com/XPIR-team/XPIR )

This version introduces three major changes:
- Compilation with cmake instead of the classic autotools
- Dependencies are no longer included (the user can install them by himself or use an included script)
- An API allowing to use XPIR as a library has been released

I hope this API can be of use to you in future projects. Let us know if any of your projects uses it and don't hesitate to ask for help if needed !

Best,

Carlos

**Comment by mortendahl** [comment]
Hi Carlos,

Thanks for the notice! The two latter points seem very interesting indeed -- looking forward to going through the code.

Best,
Morten

**Comment by Kirija** [comment]
BTW, the issue of missing exp (and db and ...) directories is now completely solved as those directories are now created at compile-time.
