### ISSUE TITLE
Changes to the 'one file' db approach

### ISSUE THREAD

**Issue by JoaoAndreSa** [XPIR-team/XPIR#24]
I am currently developing a small demo using the 'multiple files' (in folder) db but I was wondering if it would be too hard to change the 'one file' approach. In other words, what could I possible do to enable the division of the file into different asymmetric byte chunks (e.g. interpreting different type of files with different size of entries)

I know that this may involve big changes in the framework/code but for now I was just wanted to know if it is feasible or not. 

Joao Sa

**Comment by carlosaguilarmelchor** [comment]
Hi Joao,
in fact what you ask is pretty simple I have done a PR ([#25](https://github.com/XPIR-team/XPIR/pull/25)) to move the database handling files to a more appropriate directory. I therefore recommend you to wait until it is merged and follow the procedure below.

To deal with a database you need an object which inherits from DBHandler (you can find it in pir/dbhandlers/ after the PR merge). You must implement the functions in it and then you can pass the object to the PIRReplyGenerator object via its constructor. For the moment there are two objects that implement the methods in DBHandler : DBGenerator, and DBDirecrotyProcessor (both in pir/dbhandlers/). 

You can do your own object or modify one of them. Probably the easiest would be for you to modify DBDirectoryProcessor. 

**However** you should note that in PIR it is not easy to take advantage of having smaller elements : the reply must be as large as it would be if the largest database element was sent (if not the server would learn that the element sent is not among the largest database elements). In practice this means that when the reply generation is done the servers pads smaller elements with zeroes until all the elements have the same size (this is done by replyGenerator and you don't need to implement such a padding in your DBHandler object).

best,

Carlos

**Comment by JoaoAndreSa** [comment]
Thanks 👍 

For now I will keep using the available db modes (but in the meantime I will explore this way of creating a new database handling). 

One other question...  how are the files in the db folder stored, or in other words, are they 'stored randomly' or do they follow a sequence? (e.g. I have ten files: db0, db1, db2 ... db9 -> when I try to fetch file db4 can I ask for element 4 (I could not do it)? If they are 'stored randomly': db1,db4,db3... is there anyway of enforcing an order?). 

Best,
Joao Sa

**Comment by carlosaguilarmelchor** [comment]
Hi Joao,
DBDirectoryProcessor does not sorting and gets the order given by the OS. 

The file handlers are pushed into a list at line 52 during the main loop of the constructor (lines 43-57).
If you want to sort them you can do it just after line 57. As the file_list attribute is of type std::vector (see DBDirectoryProcessor.hpp:41) you can use a standard sorting algorithm directly on it (e.g. see [here](http://www.cplusplus.com/reference/algorithm/sort/)). 

I insist, you _must_ do that just after the loop (DBDirectoryProcessor.cpp:57) so that all the other processing done by DBDirectoryProcessor will take into account the files as you have ordered them.

Best,

Carlos
